{
  "admin": [
    {
      "id": "asdlkjsadf",
      "username": "أشَّف 👌",
      "email": "ashaf@gmail.com",
      "password": "123456",
      "age": 38,
      "specialty": "Admin",
      "role": "admin",
      "phoneNumber": "0123456789"
    }
  ],
  "users": [
    {
      "id": "0d64",
      "username": "Mostafa",
      "email": "mostafa.asiwy@gmail.com",
      "password": "123456",
      "phoneNumber": "0114003012",
      "age": 20,
      "gender": "male",
      "role": "client",
      "address": "",
      "cartInfo": {
        "cart": [],
        "isEmpty": true,
        "totalPrice": 0
      },
      "billsHistory": [],
      "cardNumber": "",
      "cardExpiry": "",
      "cardCVC": "",
      "cardHolder": "",
      "bannInfo": {
        "isBanned": false,
        "reason": ""
      }
    }
  ],
  "pannedEmails": [
  ],
  "products": [
    {
      "id": "SHAGHAF",
      "name": "SHAGHAF",
      "brand": "Darb",
      "desc": "Increases aqueous humor outflow to reduce IOP",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 85,
      "sales": 40,
      "url": "../src/assets/Darb/SHAGHAF.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "HAIBAH",
      "name": "HAIBAH",
      "brand": "Darb",
      "desc": "Enhances outflow of aqueous humor",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 78,
      "sales": 35,
      "url": "../src/assets/Darb/HAIBAH.png",
      "reviews": [],
      "rating": "4.0"
    },
    {
      "id": "FARIS",
      "name": "FARIS",
      "brand": "Darb",
      "desc": "Increases uveoscleral outflow",
      "category": "medicine",
      "price": 650,
      "maxQuantity": 90,
      "sales": 38,
      "url": "../src/assets/Darb/FARIS.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "ASR",
      "name": "ASR",
      "brand": "Darb",
      "desc": "Prostaglandin analogue reducing IOP",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 72,
      "sales": 32,
      "url": "../src/assets/Darb/ASR.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "BAREEQ",
      "name": "BAREEQ",
      "brand": "Darb",
      "desc": "Facilitates aqueous outflow",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 88,
      "sales": 29,
      "url": "../src/assets/Darb/BAREEQ.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "BARQ",
      "name": "BARQ",
      "brand": "Darb",
      "desc": "Beta-blocker reducing aqueous production",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 92,
      "sales": 45,
      "url": "../src/assets/Darb/BARQ.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "GHEWAA",
      "name": "GHEWAA",
      "brand": "Darb",
      "desc": "Selective beta-blocker",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 80,
      "sales": 33,
      "url": "../src/assets/Darb/GHEWAA.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "HAJIS",
      "name": "HAJIS",
      "brand": "Darb",
      "desc": "Non-selective beta-blocker",
      "category": "medicine",
      "price": 800,
      "maxQuantity": 87,
      "sales": 31,
      "url": "../src/assets/Darb/HAJIS.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "HANEEN",
      "name": "HANEEN",
      "brand": "Darb",
      "desc": "Beta-blocker with intrinsic sympathomimetic activity",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 94,
      "sales": 27,
      "url": "../src/assets/Darb/HANEEN.png",
      "reviews": [],
      "rating": "5.0"
    },
    {
      "id": "HAYAM",
      "name": "HAYAM",
      "brand": "Darb",
      "desc": "Alpha agonist reducing aqueous production",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 76,
      "sales": 36,
      "url": "../src/assets/Darb/HAYAM.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "ILHAM",
      "name": "ILHAM",
      "brand": "Darb",
      "desc": "Carbonic anhydrase inhibitor",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 89,
      "sales": 34,
      "url": "../src/assets/Darb/ILHAM.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "ISHQ",
      "name": "ISHQ",
      "brand": "Darb",
      "desc": "Reduces aqueous production",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 81,
      "sales": 28,
      "url": "../src/assets/Darb/ISHQ.png",
      "reviews": [
        {
          "clientId": "0d64",
          "clientName": "Mostafa",
          "comment": "this good",
          "rating": 4,
          "timestamp": "2025-09-04T04:00:37.954Z"
        }
      ],
      "rating": "4.0"
    },
    {
      "id": "JANNAH",
      "name": "JANNAH",
      "brand": "Darb",
      "desc": "Systemic CAI",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 93,
      "sales": 39,
      "url": "../src/assets/Darb/JANNAH.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "LAHAF",
      "name": "LAHAF",
      "brand": "Darb",
      "desc": "Rho kinase inhibitor improving outflow",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 74,
      "sales": 26,
      "url": "../src/assets/Darb/LAHAF.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "MAJD",
      "name": "MAJD",
      "brand": "Darb",
      "desc": "Cholinergic agent increasing trabecular outflow",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 91,
      "sales": 37,
      "url": "../src/assets/Darb/MAJD.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "NAJM",
      "name": "NAJM",
      "brand": "Darb",
      "desc": "Cholinergic agent increasing trabecular outflow",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 91,
      "sales": 37,
      "url": "../src/assets/Darb/NAJM.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "NEEL",
      "name": "NEEL",
      "brand": "Darb",
      "desc": "Cholinergic agent increasing trabecular outflow",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 91,
      "sales": 37,
      "url": "../src/assets/Darb/NEEL.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "SATWA",
      "name": "SATWA",
      "brand": "Darb",
      "desc": "Cholinergic agent increasing trabecular outflow",
      "category": "medicine",
      "price": 650,
      "maxQuantity": 91,
      "sales": 37,
      "url": "../src/assets/Darb/SATWA.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "SHUMOOKH",
      "name": "SHUMOOKH",
      "brand": "Darb",
      "desc": "Cholinergic agent increasing trabecular outflow",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 91,
      "sales": 37,
      "url": "../src/assets/Darb/SHUMOOKH.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "TIARA",
      "name": "TIARA",
      "brand": "Darb",
      "desc": "Cholinergic agent increasing trabecular outflow",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 91,
      "sales": 37,
      "url": "../src/assets/Darb/TIARA.png",
      "reviews": [],
      "rating": "0"
    },
    {
      "id": "WARD",
      "name": "WARD",
      "brand": "Darb",
      "desc": "Cholinergic agent increasing trabecular outflow",
      "category": "medicine",
      "price": 450,
      "maxQuantity": 91,
      "sales": 37,
      "url": "../src/assets/Darb/WARD.png",
      "reviews": [],
      "rating": "0"
    }
  ]
}